
#' @title plot_cell_mediation_plot
#' @description plot cell mediation plot
#'
#' The funciton generates the cell mediation relationships.
#' Each square represents a kind of cell type.
#' The solid line indicates a significant regulation. The arrow towards the object being regulated.
#' The dashed line indicates a non-significant regulation. The value on the line indicate the estimated coefficient.
#'
#' @param fit fitted mediation model generated by sem from lavaan
#' @param maxx the max x value, default 80
#' @param maxy the max y value, default 30
#' @param height the height of the figure, default 5
#' @param width the width of the figure, default 5
#' @param base_family the font used for text
#' @param base_size the font size used for text
#' @param usecolor default TRUE
#' @param cols the color list used for square objects, default NULL
#' @param clean the ggplot theme
#' @param whatLabels default value 'std'
#' @param regression a boolean value
#' @param mode default 1
#' @return a ggplot object
#' @export
plot_cell_mediation_plot = function (fit, maxx = 80, maxy = 30, height = 5, width = 5, base_size = 10, base_family = "Arial", title_text = "", title_size = 12,
                                     usecolor = TRUE, cols = NULL, clean = TRUE, whatLabels = "std", useLabel=FALSE, regression = TRUE, mode = 1){
  packs_to_check = c("ggplot2","lavaan","plyr","extrafont","grDevices")
  load_packages(packs_to_check)

  if ((! base_family %in% names(grDevices::X11Fonts())) | (! base_family %in% names(grDevices::postscriptFonts()))){
    font_import(pattern = base_family)
  }
  res = parameterEstimates(fit, standardized = TRUE)
  df = fit2df(fit)
  ## hidden the intercept, fixed and simplified mediationPlot
  df = df %>% filter(text!="")
  df1 = addpos(df)
  df2 = adjustPos(df1, maxx = maxx, maxy = maxy, height = height, width = width)
  df3 = df2[df2$latent == FALSE, ]
  df4 = df2[df2$latent == TRUE, ]

  p <- ggplot(data = df2, aes_string(x = "x", y = "y")) + xlim(min(df2$x) -
                                                                 12, max(df2$x) + 12) + ylim(min(df2$y) - 8, max(df2$y) + 8)
  if (nrow(df3) > 0) {
    if (usecolor) {
      p <- p + geom_rect(data = df3, aes_string(fill = "group1"),
                         xmin = df3$x - width/2, xmax = df3$x + width/2,
                         ymin = df3$y - height/2, ymax = df3$y + height/2,
                         colour = "black", alpha = 0.5)
    }
    else {
      p <- p + geom_rect(data = df3, xmin = df3$x - width/2,
                         xmax = df3$x + width/2, ymin = df3$y - height/2,
                         ymax = df3$y + height/2, color = "black", fill = "white",
                         alpha = 0.5)
    }
  }
  if (nrow(df4) > 0) {
    for (i in 1:nrow(df4)) p <- p + add_ellipse(df4$x[i],
                                                df4$y[i], height = height, width = width, fill = ifelse(usecolor,
                                                                                                        "yellow", "white"))
  }
  p <- p + geom_text(aes_string(label = "text"), size = base_size,
                     family = base_family)
  if (clean) {
    p <- p + theme_clean(base_size = base_size, base_family = base_family)
  }
  p <- p + theme(legend.position = "none")
  p2 <- p
  p <- p2
  resMeasure = res[res$op == "=~", ]
  if (nrow(resMeasure) > 0) {
    resMeasure = mergeDataPos(resMeasure, df2, whatLabels,
                              height = height, width = width)
    resMeasure = addLinetype(resMeasure)
    if (mode == 1) {
      for (i in 1:nrow(resMeasure)) {
        p <- p + addline(x1 = resMeasure$x1[i], y1 = resMeasure$y1[i],
                         x2 = resMeasure$x2[i], y2 = resMeasure$y2[i],
                         start = resMeasure$start[i], end = resMeasure$end[i],
                         linetype = resMeasure$linetype[i], height = height,
                         width = width)
        if (whatLabels != "name")
          p <- p + addlabel(x1 = resMeasure$x1[i], y1 = resMeasure$y1[i],
                            x2 = resMeasure$x2[i], y2 = resMeasure$y2[i],
                            start = resMeasure$start[i], end = resMeasure$end[i],
                            label = resMeasure$text[i], useLabel = useLabel,
                            size = base_size - 1)
      }
      p
    } else {
      p <- p + geom_segment(data = resMeasure, aes_string(x = "x",
                                                          y = "y", xend = "xend", yend = "yend"), linetype = resMeasure$linetype,
                            arrow = arrow(angle = 20, length = unit(0.3,
                                                                    "cm"), ends = "first", type = "closed"))
      if (whatLabels != "name") {
        if (useLabel)
          p <- p + geom_label(data = resMeasure, aes_string(x = "(x+xend)/2",
                                                            y = "(y+yend)/2", label = "text"), size = base_size -
                                1)
        else p <- p + geom_label(data = resMeasure, aes_string(x = "(x+xend)/2",
                                                               y = "(y+yend)/2", label = "text"), label.size = 0,
                                 size = base_size - 1)
      }
    }
  }
  p
  p2 <- p
  p <- p2
  if (regression) {
    resReg = res[res$op == "~", ]
    if (nrow(resReg) > 0) {
      resReg = mergeDataPos(resReg, df2, height = height,
                            width = width)
      resReg = addLinetype(resReg)
      if (mode == 1) {
        for (i in 1:nrow(resReg)) {
          p <- p + addline(x1 = resReg$x2[i], y1 = resReg$y2[i],
                           x2 = resReg$x1[i], y2 = resReg$y1[i], start = resReg$end[i],
                           end = resReg$start[i], linetype = resReg$linetype[i],
                           height = height, width = width)
          p
        }
        for (i in 1:nrow(resReg)) {
          p <- p + addlabel(x1 = resReg$x2[i], y1 = resReg$y2[i],
                            x2 = resReg$x1[i], y2 = resReg$y1[i], start = resReg$end[i],
                            end = resReg$start[i], label = resReg$text[i],
                            useLabel = useLabel, size = base_size - 1)
        }
        p
      }
      else {
        p <- p + geom_segment(data = resReg[substr(resReg$label,
                                                   1, 1) != "c", ], aes_string(x = "x", y = "y",
                                                                               xend = "xend", yend = "yend"), linetype = resReg[substr(resReg$label,
                                                                                                                                       1, 1) != "c", ]$linetype, arrow = arrow(angle = 20,
                                                                                                                                                                               length = unit(0.3, "cm"), type = "closed"))
        p <- p + geom_curve(data = resReg[substr(resReg$label,
                                                 1, 1) == "c", ], aes_string(x = "x", y = "y",
                                                                             xend = "xend", yend = "yend"), linetype = resReg[substr(resReg$label,
                                                                                                                                     1, 1) == "c", ]$linetype, curvature = 0.1,
                            arrow = arrow(angle = 20, length = unit(0.3,
                                                                    "cm"), type = "closed"))
        if (useLabel) {
          p <- p + geom_label(data = resReg[substr(resReg$label,
                                                   1, 1) != "c", ], aes_string(x = "(x+xend)/2",
                                                                               y = "(y+yend)/2", label = "text"), size = base_size -
                                1)
          p <- p + geom_label(data = resReg[substr(resReg$label,
                                                   1, 1) == "c", ], aes_string(x = "(x+xend)/2",
                                                                               y = "(y+yend)/2-2", label = "text"), size = base_size -
                                1)
        }
        else {
          p <- p + geom_label(data = resReg[substr(resReg$label,
                                                   1, 1) != "c", ], aes_string(x = "(x+xend)/2",
                                                                               y = "(y+yend)/2", label = "text"), label.size = 0,
                              size = base_size - 1)
          p <- p + geom_label(data = resReg[substr(resReg$label,
                                                   1, 1) == "c", ], aes_string(x = "(x+xend)/2",
                                                                               y = "(y+yend)/2-2", label = "text"), label.size = 0,
                              size = base_size - 1)
        }
        p
      }
    }
  }
  resCor = res[res$op == "~~", ]
  resCor = resCor[resCor$lhs != resCor$rhs, ] # residuals = FALSE
  if (nrow(resCor) > 0) {
    resCor = mergeDataPos(resCor, df2, whatLabels, height = height,
                          width = width)
    resCor = addLinetype(resCor)
    if (nrow(resCor[resCor$curvature == 2, ]) > 0)
      p <- p + geom_curve(data = resCor[resCor$curvature ==
                                          2, ], aes_string(x = "x", y = "y", xend = "xend",
                                                           yend = "yend"), curvature = 2.5, arrow = arrow(angle = 20,
                                                                                                          length = unit(0.2, "cm"), ends = "both", type = "closed"))
    if (nrow(resCor[resCor$curvature == -2, ]) > 0)
      p <- p + geom_curve(data = resCor[resCor$curvature ==
                                          -2, ], aes_string(x = "x", y = "y", xend = "xend",
                                                            yend = "yend"), curvature = -2.5, arrow = arrow(angle = 20,
                                                                                                            length = unit(0.2, "cm"), ends = "both", type = "closed"))
    if (nrow(resCor[resCor$curvature == -0.3, ]) > 0)
      p <- p + geom_curve(data = resCor[resCor$curvature ==
                                          -0.3, ], aes_string(x = "x", y = "y", xend = "xend",
                                                              yend = "yend"), curvature = -0.2, arrow = arrow(angle = 20,
                                                                                                              length = unit(0.2, "cm"), ends = "both", type = "closed"))
    if (nrow(resCor[resCor$curvature == 0.3, ]) > 0)
      p <- p + geom_curve(data = resCor[resCor$curvature ==
                                          0.3, ], aes_string(x = "x", y = "y", xend = "xend",
                                                             yend = "yend"), curvature = 0.2, arrow = arrow(angle = 20,
                                                                                                            length = unit(0.2, "cm"), ends = "both", type = "closed"))

  }
  p <- p +
    coord_fixed() +
    ggtitle(title_text)+
    theme(plot.title = element_text(hjust = 0.5, size = title_size))
  if (!is.null(cols)){
    p <- p +
      scale_fill_manual(values=cols)
  }
  p
}



#' @title countM
#' @description count the number of M (mediators)
#' @param group a vector contains all names of the components in the mediation model
#' @return the number of M (mediators)
countM=function(group){
  result=0
  if(length(group)>0){
    for(i in 1:length(group)){
      if(substr(group[i],1,1)=="M") result=result+1
    }
  }
  result
}



#' @title seekGroup
#' @description wrap function for seek group
#'
#' @param var a character of a component name in result table
#' @param res a data frame contains the treated summary table of the mediation model
#' @param group a vector contains names of the components used in the mediation model
#' @return the belonged group of the varaible: "X", "Y", "M1", "M2", "id,cell type"
seekGroup=function(var,res,group){
  (result=seekGroup1(var,res))
  if(result=="M"){
    count=countM(group)
    result=paste0(result,count+1)
  }
  if(result=="") result=seekGroup2(var,res,group)
  result
}



#' @title seekGroup1
#' @description condition1 for seek group
#' 
#' @param var a character of a component name in result table
#' @param res a data frame contains the treated summary table of the mediation model
#' @return the belonged group of the varaible: "X", "Y", "M1", "M2"
seekGroup1=function(var,res){
  tempgroup<-""
  tofind<-var
  mode<-0
  res4<-res[res$op=='~',]
  (Left<-res4$lhs)
  (Right<-res4$rhs)
  if(any(Left==tofind)) {
    mode<-mode+1
  }
  if(any(Right==tofind)) {
    mode<-mode+2
  }
  mode
  if(mode==3) {
    tempgroup="M"
  } else if(mode==1) {
    tempgroup="Y"
  } else if(mode==2) tempgroup="X"
  tempgroup
  if(tempgroup==""){
    res5=res[res$op=='=~',]
    if(tofind %in% res5$lhs) tempgroup="X"
  }
  tempgroup
}



#' @title seekGroup2
#' @description add position for Hidden component
#' 
#' @param var a character of a component name in result table
#' @param res a data frame contains the treated summary table of the mediation model
#' @param group a vector contains names of the components used in the mediation model
#' @return the position for component "H"
seekGroup2=function(var,res,group){
  res3=res[(res$rhs==var) & (res$op!="~~"),]
  temp=res3$lhs[1]
  if(is.na(temp)) result="X"
  else result=seekGroup1(temp,res)
  tempgroup=""
  if(result=="X") tempgroup="0"
  else if(substr(result,1,1)=="M") {
    tempgroup="H"
  } else if(result=="Y") tempgroup="5"
  paste0(tempgroup,",",temp)
}

# add position for component H
# param var a character of a component name in result table
# param res a data frame contains the treated summary table of the mediation model
# return the belonged group of the varaible:"id,cell type"
# addHpos=function(df){
#   df1=df[substr(df$group,1,1)=="H",]
#   if(nrow(df1)>0){
#     for(i in 1:nrow(df1)){
#       temp=unlist(strsplit(df1$group[i],",",fixed=TRUE))[2]
#       temp
#       pos=substr(df[df$text==temp,]$group,2,2)
#       pos
#       df[df$text==df1$text[i],]$group=paste0("H",pos,",",temp)
#     }
#   }
#   df
# }



#' @title addpos
#' @description add position
#' 
#' @param df the result used for plot the sem mediation relationship
#' @return the data.frame with position information added
addpos=function(df){
  for(i in 1:nrow(df)){
    df$group1[i]=unlist(strsplit(df$group[i],",",fixed=TRUE))[1]
    df$group2[i]=ifelse(df$group[i]==df$group1[i],"",unlist(strsplit(df$group[i],",",fixed=TRUE))[2])
  }
  dfM=df[substr(df$group,1,1)=="M",]
  (countM=nrow(dfM))
  df$x=0
  if(nrow(df[df$group1=="X",])>0) df[df$group1=="X",]$x=1
  if(nrow(df[df$group1=="M1",])>0) df[df$group1=="M1",]$x=2
  if(countM==2) {
    if(nrow(df[df$group1=="M2",])>0) df[df$group1=="M2",]$x=2
  } else if(countM>2){
    condition1 <- (substr(df$group1,1,1) =="M") & (as.numeric(substr(df$group1,2,2))<=(countM+1)%/%2)
    if(nrow(df[condition1,])>0) df[condition1,]$x=2+as.numeric(substr(df[condition1,]$group1,2,2))-1
    condition2 <- (substr(df$group1,1,1) =="M") & (as.numeric(substr(df$group1,2,2))>(countM+1)%/%2)
    if(countM%%2==0){
      if(nrow(df[condition2,])>0) df[condition2,]$x=2+as.numeric(substr(df[condition2,]$group1,2,2))-1-countM%/%2
    } else{
      if(nrow(df[condition2,])>0) df[condition2,]$x=2+as.numeric(substr(df[condition2,]$group1,2,2))-(countM+1)%/%2-0.5
    }
  }
  if(nrow(df[df$group1=="H",])>0) df[df$group1=="H",]$x=3
  if(nrow(df[df$group1=="Y",])>0) df[df$group1=="Y",]$x=3+ifelse(countM>2,(countM-1) %/% 2,0)
  if(nrow(df[df$group1=="5",])>0) df[df$group1=="5",]$x=4+ifelse(countM>2,(countM-1) %/% 2,0)
  df$y=1
  if(nrow(df>2)){
    for(i in 2:nrow(df)){
      if(substr(df$group1[i],1,1)!="H"){
        if(df$group1[i]==df$group1[i-1]) df$y[i]=df$y[i-1]+1
      } else{
        if(df$group2[i]==df$group2[i-1]) df$y[i]=df$y[i-1]+1
      }
    }
  }
  for(i in 1:countM){
    if(nrow(df[df$group1==paste0("H",i),])>0) df[df$group1==paste0("H",i),]$x= df[df$group1==paste0("M",i),]$x
  }
  if(countM>0) {
    condition=substr(df$group,1,1)=="M"
    if(nrow(df[condition,])>0) df[condition,]$y=ifelse(as.numeric(substr(df[condition,]$group1,2,2))<=(countM+1)%/%2,1,2)
  }
  if(nrow(df[substr(df$group1,1,1)=="H",])>0){
    condition=substr(df$group,1,1)=="H"
    if(nrow(df[condition,])>0) df[condition,]$y=ifelse(as.numeric(substr(df[condition,]$group1,2,2))<=(countM+1)%/%2,1,2)
  }
  df
}



#' @title distributePos
#' @description distributed the position
#' 
#' @param start the start position
#' @param end the end position
#' @param count the number of the points to segment the postion
#' @return a number vector show the accurate positions
distributePos=function(start,end,count){
  if(count==1) result=(start+end)/2
  else {
    (interval=(end-start)/(count-1))
    (result=seq(start,end,interval))
  }
  result
}



#' @title fit2df
#' @description Change the format of fit model to data.frame
#' 
#' @param fit the fitted model generated by causal mediation
#' @return a data.frame with the information of the components used in the mediation relationship and their belonged groups
fit2df = function (fit){

  packs_to_check = c("ggplot2","lavaan","plyr","extrafont","grDevices")
  load_packages(packs_to_check)

  res = parameterEstimates(fit, standardized = TRUE)
  res1 = res[res$op != ":=", ]
  text <- group <- x <- y <- latent <- c()
  count = 0
  for (i in 1:nrow(res1)) { #
    temp = res1$lhs[i]
    if (!(temp %in% text)) {
      text = c(text, temp)
      tempres = any(res1[res1$lhs == temp, ]$op == "=~")
      latent <- c(latent, tempres)
      (tempgroup = seekGroup(temp, res1, group))
      group = c(group, tempgroup)
    }
    temp = res1$rhs[i]
    if (!(temp %in% text)) {
      text = c(text, temp)
      tempres = any(res1[res1$lhs == temp, ]$op == "=~")
      latent <- c(latent, tempres)
      (tempgroup = seekGroup(temp, res1, group))
      group = c(group, tempgroup)
    }
  }
  df = data.frame(text, latent, group, stringsAsFactors = FALSE)
  # df = addHpos(df)
  df
}



#' @title adjustPos
#' @description adjust the position of the data.frame
#' 
#' @param df the data.frame of the information extracted from fitted model
#' @param maxx the max value of x, default 80
#' @param maxy the max value of y, default 30
#' @param height the height of the figure, default 3
#' @param width the width of the figure, default 5
#' @return the data.frame with adjusted positions
adjustPos=function(df,maxx=80,maxy=30,height=3,width=5){
  df$group3=df$y
  count<-nrow(df[df$group1=="0",])
  count<-c(count,nrow(df[df$group1=="X",]))
  count<-c(count,nrow(df[substr(df$group1,1,1)=="M",]))
  count<-c(count,nrow(df[df$group1=="Y",]))
  count<-c(count,nrow(df[df$group1=="5",]))
  countH<-nrow(df[substr(df$group1,1,1)=="H",])
  ## maxrow, maxcol
  res=plyr::ddply(df,"group1",nrow)
  (maxrow=max(res[nchar(res$group1)==1,]$V1))
  res$xpos=3
  condition1<- (nchar(res$group1)==2)&(as.numeric(substr(res$group1,2,2))<=(count[3]+1)%/%2)
  if(nrow(res[condition1,])>0) res[condition1,]$xpos=2
  if(nrow(res[nchar(res$group1)==1,])>0) res[nchar(res$group1)==1,]$xpos=1
  ## maxgroup :  group count except "H"
  (maxgroup=nrow(res[substr(res$group1,1,1)!="H",]))
  upperCol=res[(substr(res$group1,1,1)=="H")&(res$xpos==2),]
  lowerCol=res[(substr(res$group1,1,1)=="H")&(res$xpos==3),]
  (maxcol=maxgroup+max(sum(upperCol$V1-1),sum(lowerCol$V1-1)))

  starty=25
  endy=min(starty-(height+1)*(maxrow+1),5)

  mediation=0
  if(count[3]>0) mediation=1

  minx=5
  (stepx=5*3)
  (maxx=max(maxx,(maxgroup-1)*stepx+2*minx))
  (xpos=seq(minx,maxx,stepx))

  x<-y<-text<-group<-c()

  ## group1=="X"
  if(count[2]>0) for(i in 1:count[2]){
    x=xpos[2]
    if(nrow(df[df$group1=="X",])>0){
      df[df$group1=="X",]$x=x
      df[df$group1=="X",]$y=distributePos(starty+2,endy-2,count[2])
    }
  }

  # group1=="0"
  if(count[1]>0)  for(i in 1:count[1]){
    x=xpos[1]
    if(nrow(df[df$group1=="0",])>0){
      df[df$group1=="0",]$x=x
      df[df$group1=="0",]$y=distributePos(starty,endy,count[1])
    }
  }

  # group1=="Y"
  if(count[4]>0) {
    if(nrow(df[df$group1=="Y",])>0){
      df[df$group1=="Y",]$x=df[df$group1=="Y",]$x*stepx+minx
      df[df$group1=="Y",]$y=distributePos(starty,endy,count[4])
    }
  }

  # group1=="5"
  if(count[5]>0) {
    if(nrow(df[df$group1=="5",])>0){
      df[df$group1=="5",]$x=df[df$group1=="5",]$x*stepx+minx
      df[df$group1=="5",]$y=distributePos(starty,endy,count[5])
    }
  }

  # group1=="M"
  if(count[3]>0) {
    if(nrow(df[substr(df$group,1,1)=="M",])>0){
      (df[substr(df$group,1,1)=="M",]$x=df[substr(df$group,1,1)=="M",]$x*stepx+minx)
    }

    condition<-(substr(df$group,1,1)=="M")&(df$y==1)
    if(nrow(df[condition,])>0){
      df[condition,]$y=(starty+endy)/2+stepx+height/2
    }
    condition2<-(substr(df$group,1,1)=="M")&(df$y==2)
    if(nrow(df[condition2,])>0){
      df[condition2,]$y=(starty+endy)/2-stepx-height/2
    }

  }

  # group1=="H"
  if(countH>0) {
    condition<-(substr(df$group,1,1)=="H")&(df$y==1)
    tempcount=nrow(df[condition,])
    if(tempcount>0){
      df[condition,]$y=(starty+endy)/2+stepx*2+height/2
      df[condition,]$x=jitterPos(mean(unique(df[condition,]$x))*stepx+minx,width+1,tempcount)
    }
    condition2<-(substr(df$group,1,1)=="H")&(df$y==2)
    tempcount2=nrow(df[condition2,])
    if(tempcount2>0){
      df[condition2,]$y=(starty+endy)/2-stepx*2-height/2
      df[condition2,]$x=jitterPos(mean(unique(df[condition2,]$x))*stepx+minx,width+1,tempcount2)
    }
  }
  if(length(unique(df$group1))==2){
    if(("X" %in% unique(df$group1))&("0" %in% unique(df$group1))){
      count=nrow(df[df$group=="X",])
      for(i in 1:count){
        (temp=df[df$group=="X",]$text[i])
        if(nrow(df[df$group2==temp,])>0){
          df[df$text==temp,]$y=mean(df[df$group2==temp,]$y)
        }
      }
      df[df$group1=="X",]$x=maxx-15
      df[df$group1=="0",]$x=15
    }
  }
  (xcount=nrow(df[df$group=="X",]))
  (mcount=nrow(df[df$group %in% c("M1","M2"),]))
  if((xcount>1)&(mcount==1)){
    df[df$group=="M1",]$y=mean(df[df$group=="X",]$y)
  }
  df
}



#' output a cleaned theme for ggplot object
#'
#' remove the title, ticks, and text on both axises
#' remove background grid lines and color rectangles
#' compress the margin of the figure
#'
#' @param base_size the font size used, default 12
#' @param base_family the font family used, default Arial
#' @return the set theme
#' @export
theme_clean=function(base_size=12,base_family="Arial"){

  packs_to_check = c("ggplot2","lavaan","plyr","extrafont","grDevices")
  load_packages(packs_to_check)

  theme_grey(base_size,base_family=base_family) %+replace%
    theme(
      axis.title=element_blank(),
      axis.text=element_blank(),
      panel.background=element_blank(),
      panel.grid=element_blank(),
      axis.ticks.length=unit(0,"cm"),
      panel.spacing=unit(0,"lines"),
      plot.margin=unit(c(0,0,0,0),"lines"),
      complete=TRUE
    )
}



#' @title addLinetype
#' @description add line
#'
#' Judging line types to use according to the result. If relationship is unsignificant, use dashed line, otherwise, use solid line.
#'
#' @param res the information of the mediation relationship
#' @param pval the pvalue used to judge the significance. pvalue < pval, significant, pvalue > pval, unsignificant.
#' @return the information with annotated line type to use
addLinetype=function(res, pval = 0.05){
  res$linetype="solid"
  if(nrow(res[is.na(res$pvalue),])>0) res[is.na(res$pvalue),]$linetype="dotted"
  if(nrow(res[(res$linetype=="solid")&(res$pvalue>pval),])>0) {
    res[(res$linetype=="solid")&(res$pvalue>pval),]$linetype="dotted"
  }
  res
}



#' @title addline
#' @description Add line to the mediation plot
#' 
#' @param x1 default x1 is 0
#' @param y1 default y1 is 0
#' @param x2 default x2 is 10
#' @param y2 default y2 is 10
#' @param height default height is 3
#' @param width default width is 5
#' @param start the default start shape is ellipse
#' @param end the default end shape is rectangle
#' @param linetype the type of the line to use
#' @param size the width of the line, default 0.2
#' @param colour the color of the line, default black
#' @return a ggplot object of the line
#' @export
addline=function(x1=0,y1=0,x2=10,y2=10,height=3,width=5,start="ellipse",end="rect",linetype="solid",size=0.2,colour="black",...){
  (xend=get_endx(x1,y1,x2,y2,height=height,width=width,end=end))
  (xstart=get_startx(x1,y1,x2,y2,height=height,width=width,start=start))
  if(x1==x2){
    ystart=y1+ifelse(y1<y2,1,-1)*height/2
    yend=y2-ifelse(y1<y2,1,-1)*height/2
  } else{
    fun=function(x) (y2-y1)*(x-x1)/(x2-x1)+y1
    (yend=fun(xend))
    (ystart=fun(xstart))
  }
  geom_segment(x=xstart,y=ystart,xend=xend,yend=yend,arrow=arrow(angle=20,length=unit(0.3,"cm"),type="closed"),
               linetype=linetype,size=size,colour=colour,...)
}



#' @title get_endx
#' @description get the end value of x
#' 
#' @param x1 the x for start position
#' @param y1 the y for start position
#' @param x2 the x for end position
#' @param y2 the y for end position
#' @param height the height for the line
#' @param width the width for the line
#' @param end the target component is rectangle
#' @return the x position for draw
get_endx=function(x1,y1,x2,y2,height,width,end="rect"){
  if(abs(y1-y2)<height){
    if(end=="rect") x=x2-ifelse(x1<x2,1,-1)*width/2
    else x=x2-ifelse(x1<x2,1,-1)*width*4/5
  } else if(x1==x2){
    x=x1
  } else{
    fun1=function(x) (y2-y1)*(x-x1)/(x2-x1)+y1
    if(end=="rect"){
      if(y2>y1){
        fun2=function(x) y2-height/2
      } else {
        fun2=function(x) y2+height/2
      }
      g=function(x) fun1(x)-fun2(x)
      (x=uniroot(g,c(x1,x2))$root)
      if(x< (x2-width/2)) {
        x=x2-width/2
      } else if(x > (x2+width/2)) {
        x=x2+width/2
      }
    } else {
      if(y2>y1){
        fun2=function(x) y2-sqrt((1-(x-x2)^2/(width*4/5)^2)*(height/2)^2)
      } else {
        fun2=function(x) y2+sqrt((1-(x-x2)^2/(width*4/5)^2)*(height/2)^2)
      }
      g=function(x) fun1(x)-fun2(x)
      if(x2>x1) {
        (x=uniroot(g,c(x2,x2-width*4/5))$root)
      } else {
        (x=uniroot(g,c(x2,x2+width*4/5))$root)
      }
    }
  }
  x
}



#' @title get_startx
#' @description get the start x postion
#' 
#' @param x1 the x for start position
#' @param y1 the y for start position
#' @param x2 the x for end position
#' @param y2 the y for end position
#' @param height the height for the line
#' @param width the width for the line
#' @param start the start component is rectangle
#' @return get the x postion for draw
get_startx=function(x1,y1,x2,y2,height,width,start="rect"){
  if(abs(y1-y2) < height){
    if(start=="rect") x=x1+ifelse(x1<x2,1,-1)*width/2
    else x=x1+ifelse(x1<x2,1,-1)*width*4/5
  } else if(x1==x2){
    x=x1
  } else{
    fun1=function(x) (y2-y1)*(x-x1)/(x2-x1)+y1
    if(start=="rect"){
      if(y2>y1){
        fun2=function(x) y1+height/2
      } else {
        fun2=function(x) y1-height/2
      }
      g=function(x) fun1(x)-fun2(x)
      if(x2>x1) {
        (x=uniroot(g,c(x1,x2))$root)
      } else {
        (x=uniroot(g,c(x2,x1))$root)
      }
      if(x>x1+width/2) x=x1+width/2
      if(x<x1-width/2) x=x1-width/2
    } else {
      if(y2>y1){
        fun2=function(x) y1+sqrt((1-(x-x1)^2/(width*4/5)^2)*(height/2)^2)
      } else {
        fun2=function(x) y1-sqrt((1-(x-x1)^2/(width*4/5)^2)*(height/2)^2)
      }
      g=function(x) fun1(x)-fun2(x)
      if(x2>x1) {
        (x=uniroot(g,c(x1,x1+width*4/5))$root)
      } else {
        (x=uniroot(g,c(x1-width*4/5,x1))$root)
      }
    }
  }
  x
}



#' @title add_node
#' @description add node
#' 
#' @param x1 x1 value
#' @param y1 y1 value
#' @param height height
#' @param width width
#' @param geom geometric shape
add_node=function(x1,y1,height=5,width=5,geom="rect"){
  if(geom=="rect") add_rect(x1,y1,height,width)
  else add_ellipse(x1,y1,height=height,width=width)
}



#' @title add_rect
#' @description add node in rectangle shape
#' 
#' @param x1 x1
#' @param y1 y1
#' @param height height
#' @param width width
add_rect=function(x1,y1,height=5,width=5){
  x=x1-width/2
  xend=x1+width/2
  y=y1-height/2
  yend=y1+height/2
  geom_rect(xmin=x,xmax=xend,ymin=y,ymax=yend,fill=NA,colour="black")
}



#' @title addlabel
#' @description add label to the ggobject
#' 
#' @param x1 x1
#' @param y1 y1
#' @param x2 x2
#' @param y2 y2
#' @param height height
#' @param width width
#' @param start start
#' @param end end
#' @param label label
#' @param useLabel a boolean value
addlabel=function(x1=0,y1=0,x2=10,y2=10,height=3,width=5,start="ellipse",end="rect",label=label,useLabel,...){
  xend=get_endx(x1,y1,x2,y2,height=height,width=width,end=end)
  xstart=get_startx(x1,y1,x2,y2,height=height,width=width,start=start)
  if(x1==x2){
    ystart=y1+ifelse(y1<y2,1,-1)*height/2
    yend=y2-ifelse(y1<y2,1,-1)*height/2
  } else{
    fun=function(x) (y2-y1)*(x-x1)/(x2-x1)+y1
    yend=fun(xend)
    ystart=fun(xstart)
  }
  x=(xstart+xend)/2
  y=(ystart+yend)/2
  if(x1==x2){
    if(useLabel) geom_label(x=x,y=y,label=label,vjust=-1.5,...)
    else geom_label(x=x,y=y,label=label,label.size=0,vjust=-1.5,...)
  } else{
    if(useLabel) geom_label(x=x,y=y,label=label,...)
    else geom_label(x=x,y=y,label=label,label.size=0,...)
  }
}



#' @title mergeDataPos
#' @description merge the postion of the summary table
#' 
#' @param res the orignal result
#' @param df2 the filtered matrix
#' @param whatLabels default est for estimation
#' @param width default 5
#' @param height default 3
mergeDataPos=function(res,df2,whatLabels="est",width=5,height=3){
  #  res<-resCor;whatLabels="est";width=5;height=3
  x<-y<-xend<-yend<-label<-curvature<-group<-position1<-c()
  x1<-y1<-x2<-y2<-start<-end<-c()
  res
  xonly=-1
  if(length(unique(df2$group1))==2) xonly=1
  for(i in 1:nrow(res)){
    tempcurvature=-0.3
    tempx=df2[df2$text==res$rhs[i],]$x
    tempy=df2[df2$text==res$rhs[i],]$y
    tempxend=df2[df2$text==res$lhs[i],]$x
    tempyend=df2[df2$text==res$lhs[i],]$y
    latent=df2[df2$text==res$lhs[i],]$latent
    x1=c(x1,df2[df2$text==res$lhs[i],]$x)
    y1=c(y1,df2[df2$text==res$lhs[i],]$y)
    x2=c(x2,df2[df2$text==res$rhs[i],]$x)
    y2=c(y2,df2[df2$text==res$rhs[i],]$y)
    start=c(start,ifelse(df2[df2$text==res$lhs[i],]$latent,"ellipse","rect"))
    end=c(end,ifelse(df2[df2$text==res$rhs[i],]$latent,"ellipse","rect"))
    ## Correlation
    if(res$lhs[i]==res$rhs[i]) {
      margin=height/3
      tempcurvature=-2
      tempgroup=df2[df2$text==res$lhs[i],]$group1
      (H1group=df2[(substr(df2$group1,1,1)=="H")&(df2$group3==1),]$group1)
      (H2group=df2[(substr(df2$group1,1,1)=="H")&(df2$group3==2),]$group1)
      (M1group=df2[(substr(df2$group1,1,1)=="M")&(df2$group3==1),]$group1)
      (M2group=df2[(substr(df2$group1,1,1)=="M")&(df2$group3==2),]$group1)

      if(tempgroup %in% c("0",M1group,M2group)) {
        tempx=tempx-width/2-ifelse(latent,width/10,0)
        tempy=tempy-height/3
        tempxend=tempxend-width/2-ifelse(latent,width/10,0)
        tempyend=tempyend+height/3
        position=1
      }
      if(tempgroup %in% H1group){
        tempx=tempx-margin
        tempy=tempy+height/2
        tempxend=tempxend+margin
        tempyend=tempyend+height/2
        position=2
      }
      if(tempgroup=="5"){
        tempcurvature=2
        tempx=tempx+width/2
        tempy=tempy-margin
        tempxend=tempxend+width/2
        tempyend=tempyend+margin
        position=3
      }
      if(tempgroup %in% c("X","Y")) {
        tempcurvature=2
        tempx=tempx-margin
        tempy=tempy-height/2
        tempxend=tempxend+margin
        tempyend=tempyend-height/2
        position=4
      }
      if(tempgroup %in% H2group) {
        tempcurvature=2
        tempx=tempx-margin
        tempy=tempy-height/2
        tempxend=tempxend+margin
        tempyend=tempyend-height/2
        position=4
      }
    } else if(res$op[i]=="=~") {
      tempgroup1=df2[df2$text==res$rhs[i],]$group1
      if(length(tempgroup1)>0){
        if(tempgroup1=="0") tempx=tempx+width/2

        (H1group=df2[(substr(df2$group1,1,1)=="H")&(df2$group3==1),]$group1)
        (H2group=df2[(substr(df2$group1,1,1)=="H")&(df2$group3==2),]$group1)
        (M1group=df2[(substr(df2$group1,1,1)=="M")&(df2$group3==1),]$group1)
        (M2group=df2[(substr(df2$group1,1,1)=="M")&(df2$group3==2),]$group1)
        if(tempgroup1 %in% H1group) tempy=tempy-height/2
        if(tempgroup1 %in% H2group) tempy=tempy+height/2
        if(tempgroup1=="5") tempx=tempx-width/2
      }
      tempgroup=df2[df2$text==res$lhs[i],]$group1
      if(length(tempgroup)>0){
        if(tempgroup %in% M1group) tempyend=tempyend+height/2
        if(tempgroup %in% M2group) tempyend=tempyend-height/2
        if(tempgroup=="Y") tempxend=tempxend+width/2+ifelse(latent,width*3/10,0)
        if(tempgroup=="X") tempxend=tempxend-width/2-ifelse(latent,width*3/10,0)
      }
    } else if(res$op[i] %in% c("~","~~")) {
      position=1
      tempgroup1=df2[df2$text==res$rhs[i],]$group1
      if(length(tempgroup1)>0){
        (H1group=df2[(substr(df2$group1,1,1)=="H")&(df2$group3==1),]$group1)
        (H2group=df2[(substr(df2$group1,1,1)=="H")&(df2$group3==2),]$group1)
        (M1group=df2[(substr(df2$group1,1,1)=="M")&(df2$group3==1),]$group1)
        (M2group=df2[(substr(df2$group1,1,1)=="M")&(df2$group3==2),]$group1)
        latent=df2[df2$text==res$rhs[i],]$latent
        if(tempgroup1=="0") tempx=tempx+width/2
        if(tempgroup1 %in% H1group) tempy=tempy-height/2
        if(tempgroup1 %in% H2group) tempy=tempy+height/2
        if(tempgroup1=="5") tempx=tempx-width/2
        if(tempgroup1 %in% M1group) tempy=tempy-height/2
        if(tempgroup1 %in% M2group) tempy=tempy+height/2
        if(tempgroup1=="Y") tempx=tempx-width/2-ifelse(latent,width*3/10,0)
        if(tempgroup1=="X") tempx=tempx+width/2+ifelse(latent,width*3/10,0)
      }
      tempgroup=df2[df2$text==res$lhs[i],]$group1
      if(length(tempgroup)>0){
        latent=df2[df2$text==res$lhs[i],]$latent
        if(tempgroup=="0") tempxend=tempxend+width/2
        if(tempgroup %in% H1group) tempyend=tempyend-height/2
        if(tempgroup %in% H2group) tempyend=tempyend+height/2
        if(tempgroup=="5") tempxend=tempxend-width/2
        if(tempgroup %in% M1group) tempyend=tempyend-height/2
        if(tempgroup %in% M2group) tempyend=tempyend+height/2

        if(tempgroup=="Y") {
          tempxend=tempxend-width/2-ifelse(latent,width*3/10,0)
          position=1
        }
        if(tempgroup=="X") tempxend=tempxend+width/2+ifelse(latent,width*3/10,0)
      }
    }
    x=c(x,tempx)
    y=c(y,tempy)
    xend=c(xend,tempxend)
    yend=c(yend,tempyend)
    #df2
    if(res$op[i]=="~~") {
      curvature=c(curvature,tempcurvature)
      group=c(group,tempgroup)
      position1=c(position1,position)
    }
  }
  res$x=x
  res$y=y
  res$xend=xend
  res$yend=yend
  res$x1=x1
  res$y1=y1
  res$x2=x2
  res$y2=y2
  res$start=start
  res$end=end

  if(res$op[i]=="~~") {
    res$curvature=curvature
    res$group=group
    res$position=position1

  }
  if(whatLabels=="std") res$text=res[["std.all"]]
  else if(whatLabels=="name") res$text=res$label
  else res$text=res$est
  if(is.numeric(res$text)) res$text=sprintf("%0.2f",res$text)
  select=((res$op=="~~")&(res$lhs!=res$rhs)&(res$group=="X"))
  if(sum(select)>0){
    res[select,]$x= res[select,]$x1+xonly*width/2+xonly*ifelse(res[select,]$start=="rect",0,width*3/10)
    res[select,]$xend= res[select,]$x2+xonly*width/2+xonly*ifelse(res[select,]$start=="rect",0,width*3/10)
    res[select,]$curvature=0.3*xonly
    if(xonly) res[select,]$position=3
    else res[select,]$position=1
  }
  select=((res$op=="~~")&(res$lhs!=res$rhs)&(res$group=="Y"))
  if(sum(select)>0){
    res[select,]$x= res[select,]$x1+width/2+ifelse(res[select,]$start=="rect",0,width*3/10)
    res[select,]$xend= res[select,]$x2+width/2+ifelse(res[select,]$start=="rect",0,width*3/10)
    res[select,]$curvature=0.3
    res[select,]$position=3
  }
  select=((res$op=="~~")&(res$lhs!=res$rhs)&(res$group=="H1"))
  if(sum(select)>0){
    res[select,]$x= res[select,]$x1
    res[select,]$xend = res[select,]$x2
    res[select,]$y = res[select,]$y1+height/2
    res[select,]$yend = res[select,]$y2+height/2
    res[select,]$curvature=-0.3
    res[select,]$position=2
  }
  select=((res$op=="~~")&(res$lhs!=res$rhs)&(res$group=="5"))
  if(sum(select)>0){
    res[select,]$x= res[select,]$x1+width/2
    res[select,]$xend = res[select,]$x2+width/2
    res[select,]$y = res[select,]$y1
    res[select,]$yend = res[select,]$y2
    res[select,]$curvature=-0.3
    res[select,]$position=3
  }
  res
}



